import type { Metadata } from "next";
import { Tajawal } from "next/font/google";
import localFont from "next/font/local";
import "../styles/main.css";

//TAJWAL
export const tajawal = Tajawal({
  subsets: ["arabic"],
  weight: ["200", "300", "400", "500", "700", "800", "900"],
  variable: "--font-tajawal",
});

// Avant-Grade Regular
export const AminRegular = localFont({
  src: "../assets/fonts/Amin-Regular.woff2",
  variable: "--font-amin-regular",
});

// Avant-Garde
export const AvantGarde = localFont({
  src: "../assets/fonts/Avant-Garde.woff2",
  variable: "--font-avant-garde",
});


import { ThemeProvider } from "@/providers/theme-provider"

export const metadata: Metadata = {
  title: "Teacher Panel",
  description: "Generated by UpTech Solutions Team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl" suppressHydrationWarning>
      <body
        className={` ${tajawal.variable} ${AminRegular.variable} ${AvantGarde.variable} ${tajawal.className}  antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
